## 该原始配置文件已弃用，现转为nacos配置中心
#
## 服务端口
#server:
#  port: 8081
#
#spring:
#  # 服务名
#  application:
#    name: service-oss
#  # 环境设置：dev、test、prod
#  profiles:
#    active: dev
#  # nacos服务地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
## 阿里云 OSS
## 不同服务器，地址不同
#aliyun:
#  oss:
#    file:
#      endpoint: oss-cn-beijing.aliyuncs.com
#      keyid:
#      keysecret:
#      # bucket可以在控制台创建，也可以使用java代码创建
#      buckername: invictusqiu